// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuH62homg_EZBSFEamWRFrv-GlsZQP9hk',
    appId: '1:313751884507:android:452af92e75521fa8c572fe',
    messagingSenderId: '313751884507',
    projectId: 'creditsea-b9955',
    storageBucket: 'creditsea-b9955.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5q0GFDTN2Pjf9GzSVc6Qh6Ec0t23DJg',
    appId: '1:313751884507:web:eba00ce1b1270d8cc572fe',
    messagingSenderId: '313751884507',
    projectId: 'creditsea-b9955',
    authDomain: 'creditsea-b9955.firebaseapp.com',
    storageBucket: 'creditsea-b9955.firebasestorage.app',
    measurementId: 'G-FHFNRFKFEN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8W0Rpa-J7s8hqSHLbF0ank_nnlD826s',
    appId: '1:313751884507:ios:d187f2544d6900aec572fe',
    messagingSenderId: '313751884507',
    projectId: 'creditsea-b9955',
    storageBucket: 'creditsea-b9955.firebasestorage.app',
    iosBundleId: 'com.example.creditsea',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8W0Rpa-J7s8hqSHLbF0ank_nnlD826s',
    appId: '1:313751884507:ios:d187f2544d6900aec572fe',
    messagingSenderId: '313751884507',
    projectId: 'creditsea-b9955',
    storageBucket: 'creditsea-b9955.firebasestorage.app',
    iosBundleId: 'com.example.creditsea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq5q0GFDTN2Pjf9GzSVc6Qh6Ec0t23DJg',
    appId: '1:313751884507:web:57f34fdc1a7b0458c572fe',
    messagingSenderId: '313751884507',
    projectId: 'creditsea-b9955',
    authDomain: 'creditsea-b9955.firebaseapp.com',
    storageBucket: 'creditsea-b9955.firebasestorage.app',
    measurementId: 'G-ZJ889HD1K4',
  );

}